openapi: 3.0.0
info:
  title: ProcedureQuoteService
  version: '1.0'
paths:
  /getQuote:
    get:
      summary: Retrieves the median cost for medical procedures by a specific doctor.
      description: Get the median cost estimate based on historical data from a specific doctor. If procedureCode is provided, returns median for that specific procedure. If procedureCode is omitted, returns median for all procedures by the doctor.
      operationId: getQuote
      parameters:
        - name: doctorName
          in: query
          required: true
          schema:
            type: string
          description: The name of the doctor (e.g., "Sarah Johnson", "Michael Chen").
        - name: procedureCode
          in: query
          required: false
          schema:
            type: string
          description: Optional. The unique code identifying a specific procedure (e.g., "CONS001", "SURG001"). If omitted, returns median for all procedures by the doctor.
      responses:
        '200':
          description: Median cost retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  doctorName:
                    type: string
                  procedureCode:
                    type: string
                  procedureName:
                    type: string
                  medianCost:
                    type: number
                    format: float
                  sampleCount:
                    type: integer
                  costRange:
                    type: object
                    properties:
                      min:
                        type: number
                        format: float
                      max:
                        type: number
                        format: float
        '400':
          description: Missing required parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: No procedures found for the specified doctor and procedure code.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string